### ISSUE TITLE
ImportError: dlopen(/Users/alamin/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 0x0002): Library not loaded: @rpath/libffi.6.dylib

### ISSUE THREAD

**Issue by alaminzju** [xikanfeng2/SCSilicon#1]
Hi,
Thank you for your nice software. I want to inform you that I have tried several times to install scsilicon according to the instruction but failed. I have installed all of the dependencies successfully but it showed the following errors:
`Alamin-Mac:SCSilicon` alamin$ python setup.py installI 
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    import setuptools
  File "/Users/alamin/miniconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 18, in <module>
    from setuptools.dist import Distribution
  File "/Users/alamin/miniconda3/lib/python3.7/site-packages/setuptools/dist.py", line 37, in <module>
    from setuptools import windows_support
  File "/Users/alamin/miniconda3/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/Users/alamin/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array

> ImportError: dlopen(/Users/alamin/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 0x0002): Library not loaded: @rpath/libffi.6.dylib

  Referenced from: /Users/alamin/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: tried: '/Users/alamin/miniconda3/lib/libffi.6.dylib' (no such file), '/Users/alamin/miniconda3/lib/libffi.6.dylib' (no such file), '/Users/alamin/miniconda3/lib/libffi.6.dylib' (no such file), '/Users/alamin/miniconda3/lib/python3.7/lib-dynload/../../libffi.6.dylib' (no such file), '/Users/alamin/miniconda3/lib/libffi.6.dylib' (no such file), '/Users/alamin/miniconda3/lib/libffi.6.dylib' (no such file), '/Users/alamin/miniconda3/lib/libffi.6.dylib' (no such file), '/Users/alamin/miniconda3/lib/python3.7/lib-dynload/../../libffi.6.dylib' (no such file), '/Users/alamin/miniconda3/lib/libffi.6.dylib' (no such file), '/Users/alamin/miniconda3/lib/libffi.6.dylib' (no such file), '/Users/alamin/miniconda3/bin/../lib/libffi.6.dylib' (no such file), '/Users/alamin/miniconda3/lib/libffi.6.dylib' (no such file), '/Users/alamin/miniconda3/lib/libffi.6.dylib' (no such file), '/Users/alamin/miniconda3/bin/../lib/libffi.6.dylib' (no such file), '/usr/local/lib/libffi.6.dylib' (no such file), '/usr/lib/libffi.6.dylib' (no such file)`

Could you please give your suggestion to solve this issue?

**Comment by alaminzju** [comment]
The problem is "@rpath/libffi.6.dylib". This problem solved by the following command before installing this package:
`ln -s libffi.8.dylib libffi.6.dylib`
